### ISSUE TITLE
mising segments after union

### ISSUE THREAD

**Issue by typemytype** [typemytype/booleanOperations#27]
```
<?xml version="1.0" encoding="UTF-8"?>
<glyph name="A" format="1">
  <advance width="0"/>
  <outline>
    <contour>
      <point x="282" y="50" type="line"/>
      <point x="117" y="50" type="line"/>
      <point x="117" y="0" type="line"/>
      <point x="282" y="0" type="line"/>
    </contour>
    <contour>
      <point x="90" y="190" type="line"/>
      <point x="90" y="30" type="line" smooth="yes"/>
      <point x="90" y="13"/>
      <point x="98" y="0"/>
      <point x="117" y="0" type="curve" smooth="yes"/>
      <point x="134" y="0"/>
      <point x="144" y="13"/>
      <point x="144" y="30" type="curve" smooth="yes"/>
      <point x="144" y="190" type="line"/>
    </contour>
    <contour>
      <point x="382" y="150" type="line"/>
      <point x="217" y="150" type="line"/>
      <point x="217" y="100" type="line"/>
      <point x="382" y="100" type="line"/>
    </contour>
    <contour>
      <point x="190" y="290" type="line"/>
      <point x="190" y="130" type="line" smooth="yes"/>
      <point x="190" y="113"/>
      <point x="198" y="100"/>
      <point x="217" y="100" type="curve"/>
      <point x="244" y="130" type="line"/>
      <point x="244" y="290" type="line"/>
    </contour>
  </outline>
</glyph>
```

**Comment by anthrotype** [comment]
It turns out, using the upstream [pyclipper](https://github.com/greginvm/pyclipper) instead of the outdated one that's bundled in booleanOperations appears to fix the issue!  🎯 


<img width="415" alt="screenshot 2016-09-10 19 04 36" src="https://cloud.githubusercontent.com/assets/6939968/18412565/a85d88b0-7789-11e6-9c46-05b64e85630f.png">

<img width="435" alt="screenshot 2016-09-10 19 06 05" src="https://cloud.githubusercontent.com/assets/6939968/18412570/b34e10fa-7789-11e6-9d22-f851f75066cb.png">

<img width="438" alt="screenshot 2016-09-10 19 04 30" src="https://cloud.githubusercontent.com/assets/6939968/18412572/b7559f24-7789-11e6-97ab-2c89b13436b2.png">

I'll prepare a pull request soon.

**Comment by typemytype** [comment]
super!

I will opensource my test ufo, but first I have to ask all the contributors if Im allowed to publish some of their glyphs.

gr Frederik
www.typemytype.com
