### ISSUE TITLE
exceptions

### ISSUE THREAD

**Issue by typemytype** [typemytype/booleanOperations#41]
It super nice to have some exceptions raised

but its also a hard: fe a contour with 2 line segments, so no area, would raise an exception for the whole glyph. Visually this contour would always disappear.

https://github.com/typemytype/booleanOperations/blob/master/Lib/booleanOperations/booleanOperationManager.py#L41

In some cases a silent fail is nice. Im unsure what else pyclipper.ClipperException is catching when adding a path.

**Comment by typemytype** [comment]
part of the solution

https://github.com/typemytype/booleanOperations/commit/8dc6c6ac8a372ff919ce9ed0e02ad2bc77f81e63

**Comment by anthrotype** [comment]
Yeah, I changed from `AddPaths` (which only raises when all input contours are invalid for clipping) to `AddPath` in a for loop, so now it raises if any one is invalid.
But maybe you're right, it's a bit too much.
We can revert to using `AddPaths` by default if you like, and have an option to raise if any single one is invalid.

My understanding is that subject contours are invalid if they have no area, or if they are open. Clipping paths can be open (unlike subject ones), but we currently do not use the `closed=True` keyword argument of `AddPath` and `AddPaths`, thus we always assume that the input contours are closed (which may not always be).

By the way, do you know the Clipper library also exports a `Area` method?

https://github.com/greginvm/pyclipper/blob/master/pyclipper/pyclipper.pyx#L279-L291

It should be faster than the pure-python AreaPen as it's written in C++, and should also be accurate since Clipper also uses that to compute the orientation of paths.

**Comment by anthrotype** [comment]
note that the `pyclipper.Area` function only works on polygons, not on bezier contours.

**Comment by typemytype** [comment]
using `pyClipper.Area` and ignore those would be fine, as those will fail in pyClipper and do nothing the the operation

Using open contours is an option an implementation can handle. The choice not to add them or closing them should be made elsewhere.

**Comment by typemytype** [comment]
see https://github.com/typemytype/booleanOperations/commit/e65175badaa304578087cf921724fbc53676cc52

**Comment by anthrotype** [comment]
That's good, thanks

**Comment by anthrotype** [comment]
should we tag 0.6.3?

It's easy to do from the Github website:
https://github.com/typemytype/booleanOperations/releases/new

**Comment by typemytype** [comment]
Yep, a tag touch would be nice

**Comment by anthrotype** [comment]
done https://github.com/typemytype/booleanOperations/releases/tag/0.6.3

**Comment by typemytype** [comment]
Thanks!
